# Generated by Django 5.2.3 on 2025-07-16 03:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaIngrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Nombre de Categoría",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
            ],
            options={
                "verbose_name": "Categoría de Ingrediente",
                "verbose_name_plural": "Categorías de Ingredientes",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Nombre de la Empresa",
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Razón Social",
                    ),
                ),
                (
                    "rfc",
                    models.CharField(
                        blank=True, max_length=13, null=True, verbose_name="RFC"
                    ),
                ),
                (
                    "direccion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Dirección Fiscal"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email de Contacto",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Activo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Nombre del Proveedor"
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Razón Social",
                    ),
                ),
                (
                    "rfc",
                    models.CharField(
                        blank=True, max_length=13, null=True, verbose_name="RFC"
                    ),
                ),
                (
                    "direccion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Dirección Fiscal"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email de Contacto",
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoEstablecimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Tipo de Establecimiento",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
            ],
            options={
                "verbose_name": "Tipo de Establecimiento",
                "verbose_name_plural": "Tipos de Establecimiento",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="UnidadMedida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Nombre de la Unidad",
                    ),
                ),
                (
                    "abreviatura",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        unique=True,
                        verbose_name="Abreviatura",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("peso", "Peso"),
                            ("volumen", "Volumen"),
                            ("cantidad", "Cantidad"),
                            ("longitud", "Longitud"),
                            ("otro", "Otro"),
                        ],
                        default="cantidad",
                        max_length=20,
                        null=True,
                        verbose_name="Tipo de Unidad",
                    ),
                ),
                (
                    "factor_a_unidad_base",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        default=1.0,
                        max_digits=10,
                        null=True,
                        verbose_name="Factor a Unidad Base",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidad de Medida",
                "verbose_name_plural": "Unidades de Medida",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Establecimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del Establecimiento"
                    ),
                ),
                (
                    "direccion",
                    models.TextField(blank=True, null=True, verbose_name="Dirección"),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email de Contacto",
                    ),
                ),
                (
                    "fecha_apertura",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Apertura"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="establecimientos",
                        to="ixcaui_app.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ixcaui_app.tipoestablecimiento",
                        verbose_name="Tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Establecimiento",
                "verbose_name_plural": "Establecimientos",
                "ordering": ["empresa__nombre", "nombre"],
                "unique_together": {("empresa", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "tipo_usuario",
                    models.CharField(
                        choices=[
                            ("empresa", "Usuario de Empresa/Establecimiento"),
                            ("proveedor", "Usuario de Proveedor"),
                            ("tochinalli_admin", "Administrador Global Tochinalli"),
                        ],
                        default="empresa",
                        max_length=20,
                        verbose_name="Tipo de Usuario",
                    ),
                ),
                (
                    "restringido_a_establecimiento",
                    models.BooleanField(
                        default=False,
                        verbose_name="Restringido a un Establecimiento Específico",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="ixcaui_app_user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="ixcaui_app_user_permissions_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "empresa_asociada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usuarios",
                        to="ixcaui_app.empresa",
                        verbose_name="Empresa Asociada",
                    ),
                ),
                (
                    "establecimiento_asociado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usuarios_restringidos",
                        to="ixcaui_app.establecimiento",
                        verbose_name="Establecimiento Asociado",
                    ),
                ),
                (
                    "proveedor_asociado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usuarios",
                        to="ixcaui_app.proveedor",
                        verbose_name="Proveedor Asociado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario Tochinalli",
                "verbose_name_plural": "Usuarios Tochinalli",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_evento",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nombre del Evento",
                    ),
                ),
                (
                    "fecha_evento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha del Evento"
                    ),
                ),
                (
                    "numero_comensales",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Número de Comensales"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descripción del Evento"
                    ),
                ),
                (
                    "presupuesto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Presupuesto",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Activo"
                    ),
                ),
                (
                    "establecimiento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="ixcaui_app.establecimiento",
                        verbose_name="Establecimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "ordering": ["fecha_evento"],
            },
        ),
        migrations.CreateModel(
            name="Ingrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nombre del Ingrediente",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("materia_prima", "Materia Prima"),
                            ("producto_intermedio", "Producto Intermedio"),
                        ],
                        default="materia_prima",
                        max_length=50,
                        null=True,
                        verbose_name="Tipo de Ingrediente",
                    ),
                ),
                (
                    "costo_unitario_base",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=0.0,
                        max_digits=10,
                        null=True,
                        verbose_name="Costo Unitario Base",
                    ),
                ),
                (
                    "es_alergeno",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="Es Alérgeno"
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ixcaui_app.categoriaingrediente",
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "establecimiento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredientes",
                        to="ixcaui_app.establecimiento",
                        verbose_name="Establecimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingrediente",
                "verbose_name_plural": "Ingredientes",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="NivelJerarquico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nombre del Nivel",
                    ),
                ),
                (
                    "nivel",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="Nivel Numérico",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="niveles_jerarquicos",
                        to="ixcaui_app.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nivel Jerárquico",
                "verbose_name_plural": "Niveles Jerárquicos",
                "ordering": ["nivel"],
            },
        ),
        migrations.CreateModel(
            name="OrdenDeCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_orden",
                    models.DateField(auto_now_add=True, verbose_name="Fecha de Orden"),
                ),
                (
                    "fecha_entrega_esperada",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Entrega Esperada"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("enviada", "Enviada"),
                            ("recibida", "Recibida"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=20,
                        null=True,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "total_orden",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                        verbose_name="Total de la Orden",
                    ),
                ),
                (
                    "creada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordenes_compra_creadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creada Por",
                    ),
                ),
                (
                    "establecimiento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordenes_compra",
                        to="ixcaui_app.establecimiento",
                        verbose_name="Establecimiento",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordenes_compra_recibidas",
                        to="ixcaui_app.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de Compra",
                "verbose_name_plural": "Órdenes de Compra",
                "ordering": ["-fecha_orden"],
            },
        ),
        migrations.CreateModel(
            name="ProductoProveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Precio Unitario",
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Activo"
                    ),
                ),
                (
                    "ingrediente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proveedores_oferta",
                        to="ixcaui_app.ingrediente",
                        verbose_name="Ingrediente",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos_ofrecidos",
                        to="ixcaui_app.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
                (
                    "unidad_medida_compra",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ixcaui_app.unidadmedida",
                        verbose_name="Unidad de Medida de Compra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto de Proveedor",
                "verbose_name_plural": "Productos de Proveedores",
                "ordering": ["proveedor__nombre", "ingrediente__nombre"],
                "unique_together": {("proveedor", "ingrediente")},
            },
        ),
        migrations.CreateModel(
            name="RecetaPrincipal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nombre de la Receta Principal",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "rendimiento_cantidad",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Cantidad de Rendimiento",
                    ),
                ),
                (
                    "costo_total_produccion",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                        verbose_name="Costo Total de Producción",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recetas_principales",
                        to="ixcaui_app.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "unidad_rendimiento",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ixcaui_app.unidadmedida",
                        verbose_name="Unidad de Rendimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receta Principal",
                "verbose_name_plural": "Recetas Principales",
                "ordering": ["nombre"],
                "unique_together": {("empresa", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="SubcategoriaIngrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nombre de Subcategoría",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategorias",
                        to="ixcaui_app.categoriaingrediente",
                        verbose_name="Categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcategoría de Ingrediente",
                "verbose_name_plural": "Subcategorías de Ingredientes",
                "ordering": ["nombre"],
                "unique_together": {("categoria", "nombre")},
            },
        ),
        migrations.AddField(
            model_name="ingrediente",
            name="subcategoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ixcaui_app.subcategoriaingrediente",
                verbose_name="Subcategoría",
            ),
        ),
        migrations.CreateModel(
            name="SubReceta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nombre de la Sub-Receta",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "rendimiento_cantidad",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Cantidad de Rendimiento",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subrecetas",
                        to="ixcaui_app.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "unidad_rendimiento",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ixcaui_app.unidadmedida",
                        verbose_name="Unidad de Rendimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub-Receta",
                "verbose_name_plural": "Sub-Recetas",
                "ordering": ["nombre"],
                "unique_together": {("empresa", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="ItemReceta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_componente",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ingrediente", "Ingrediente"),
                            ("sub_receta", "Sub-Receta"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Tipo de Componente",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "ingrediente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ixcaui_app.ingrediente",
                        verbose_name="Ingrediente",
                    ),
                ),
                (
                    "receta_principal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ixcaui_app.recetaprincipal",
                        verbose_name="Receta Principal",
                    ),
                ),
                (
                    "sub_receta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ixcaui_app.subreceta",
                        verbose_name="Sub-Receta",
                    ),
                ),
                (
                    "unidad_medida",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ixcaui_app.unidadmedida",
                        verbose_name="Unidad de Medida",
                    ),
                ),
            ],
            options={
                "verbose_name": "Componente de Receta",
                "verbose_name_plural": "Componentes de Receta",
            },
        ),
        migrations.AddField(
            model_name="ingrediente",
            name="unidad_medida_base",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ixcaui_app.unidadmedida",
                verbose_name="Unidad de Medida Base",
            ),
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre del Área"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "establecimiento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="ixcaui_app.establecimiento",
                        verbose_name="Establecimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Área",
                "verbose_name_plural": "Áreas",
                "ordering": ["establecimiento__nombre", "nombre"],
                "unique_together": {("establecimiento", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="ItemOrdenDeCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_pedida",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Cantidad Pedida",
                    ),
                ),
                (
                    "cantidad_recibida",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                        verbose_name="Cantidad Recibida",
                    ),
                ),
                (
                    "precio_unitario_final",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Precio Unitario Final",
                    ),
                ),
                (
                    "precio_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                        verbose_name="Precio Total",
                    ),
                ),
                (
                    "orden_compra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items_orden",
                        to="ixcaui_app.ordendecompra",
                        verbose_name="Orden de Compra",
                    ),
                ),
                (
                    "producto_proveedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ixcaui_app.productoproveedor",
                        verbose_name="Producto de Proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de Orden de Compra",
                "verbose_name_plural": "Ítems de Órdenes de Compra",
                "unique_together": {("orden_compra", "producto_proveedor")},
            },
        ),
        migrations.CreateModel(
            name="Puesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nombre del Puesto",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "establecimiento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puestos",
                        to="ixcaui_app.establecimiento",
                        verbose_name="Establecimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Puesto",
                "verbose_name_plural": "Puestos",
                "ordering": ["establecimiento__nombre", "nombre"],
                "unique_together": {("establecimiento", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="EventoReceta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_a_servir",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Cantidad a Servir",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recetas_servidas",
                        to="ixcaui_app.evento",
                        verbose_name="Evento",
                    ),
                ),
                (
                    "receta_principal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ixcaui_app.recetaprincipal",
                        verbose_name="Receta Principal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receta de Evento",
                "verbose_name_plural": "Recetas de Evento",
                "unique_together": {("evento", "receta_principal")},
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nombre del Producto",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "precio_venta",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Precio de Venta",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="productos/",
                        verbose_name="Imagen del Producto",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Activo"
                    ),
                ),
                (
                    "empresa_asociada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="ixcaui_app.empresa",
                        verbose_name="Empresa Asociada",
                    ),
                ),
                (
                    "establecimiento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="ixcaui_app.establecimiento",
                        verbose_name="Establecimiento",
                    ),
                ),
                (
                    "receta_principal",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ixcaui_app.recetaprincipal",
                        verbose_name="Receta Principal Asociada",
                    ),
                ),
                (
                    "unidad_medida",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ixcaui_app.unidadmedida",
                        verbose_name="Unidad de Medida de Venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["nombre"],
                "unique_together": {("empresa_asociada", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="Inventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Cantidad en Inventario",
                    ),
                ),
                (
                    "fecha_ultima_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Última Actualización"
                    ),
                ),
                (
                    "establecimiento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventarios",
                        to="ixcaui_app.establecimiento",
                        verbose_name="Establecimiento",
                    ),
                ),
                (
                    "ingrediente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventarios",
                        to="ixcaui_app.ingrediente",
                        verbose_name="Ingrediente",
                    ),
                ),
                (
                    "unidad_medida",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ixcaui_app.unidadmedida",
                        verbose_name="Unidad de Medida",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventario",
                "verbose_name_plural": "Inventarios",
                "ordering": ["establecimiento__nombre", "ingrediente__nombre"],
                "unique_together": {("establecimiento", "ingrediente")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="ingrediente",
            unique_together={("establecimiento", "nombre")},
        ),
    ]
