# Generated by Django 5.2.3 on 2025-07-16 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ixcaui_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("falta_stock", "Falta de Stock"),
                            ("sustitucion_propuesta", "Sustitución Propuesta"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "cantidad_faltante",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("mensaje", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[("pendiente", "Pendiente"), ("resuelta", "Resuelta")],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ixcaui_app.area",
                    ),
                ),
                (
                    "establecimiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ixcaui_app.establecimiento",
                    ),
                ),
                (
                    "ingrediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ixcaui_app.ingrediente",
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IngredienteSustituto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prioridad", models.PositiveIntegerField()),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "ingrediente_principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sustitutos",
                        to="ixcaui_app.ingrediente",
                    ),
                ),
                (
                    "ingrediente_sustituto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usado_como_sustituto",
                        to="ixcaui_app.ingrediente",
                    ),
                ),
            ],
            options={
                "ordering": ["prioridad"],
                "unique_together": {("ingrediente_principal", "ingrediente_sustituto")},
            },
        ),
        migrations.CreateModel(
            name="InventarioEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Stock Global",
                    ),
                ),
                ("fecha_ultima_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventarios_empresa",
                        to="ixcaui_app.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "ingrediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventarios_empresa",
                        to="ixcaui_app.ingrediente",
                        verbose_name="Ingrediente",
                    ),
                ),
                (
                    "unidad_medida",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ixcaui_app.unidadmedida",
                        verbose_name="Unidad de Medida",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventario de la Empresa",
                "verbose_name_plural": "Inventarios de Empresa",
                "ordering": ["empresa__nombre", "ingrediente__nombre"],
                "unique_together": {("empresa", "ingrediente")},
            },
        ),
        migrations.CreateModel(
            name="InventarioEstablecimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Stock Actual",
                    ),
                ),
                (
                    "stock_minimo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Stock Mínimo",
                    ),
                ),
                ("fecha_ultima_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "establecimiento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventarios_establecimiento",
                        to="ixcaui_app.establecimiento",
                        verbose_name="Establecimiento",
                    ),
                ),
                (
                    "ingrediente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventarios_establecimiento",
                        to="ixcaui_app.ingrediente",
                        verbose_name="Ingrediente",
                    ),
                ),
                (
                    "unidad_medida",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ixcaui_app.unidadmedida",
                        verbose_name="Unidad de Medida",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventario del Establecimiento",
                "verbose_name_plural": "Inventarios de Establecimiento",
                "ordering": ["establecimiento__nombre", "ingrediente__nombre"],
                "unique_together": {("establecimiento", "ingrediente")},
            },
        ),
        migrations.DeleteModel(
            name="Inventario",
        ),
    ]
